//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinallLaibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBook
    {
        public int BookId { get; set; }
        [DisplayName("Book Name")]
        [Required(ErrorMessage = "Please enter book name.")]
        [StringLength(50, MinimumLength = 10)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Only letters are allowed.")]
        public string BookTitle { get; set; }
        [DisplayName("Category")]
        [Required(ErrorMessage = "Please select category.")]

        public string BookCategory { get; set; }
        [DisplayName("Author Name")]
        [StringLength(50, MinimumLength = 10)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Only letters are allowed.")]
        [Required(ErrorMessage = "Please select category.")]

        public string BookAuthor { get; set; }
        [DisplayName("Book Copies")]
        [Required(ErrorMessage = "Please enter book copies.")]
        public Nullable<int> BookCopies { get; set; }
        [DisplayName("Publish Name")]
        [Required(ErrorMessage = "Please enter publish name.")]
        public string BookPub { get; set; }
        [DisplayName("Publisher Name")]
        [Required(ErrorMessage = "Please enter publisher name.")]
        public string BookPubName { get; set; }
        [DisplayName("Book No.")]
        [Required(ErrorMessage = "Please enter book no.")]
        public string BookISBN { get; set; }
        [DisplayName("Publish Year")]
        [Required(ErrorMessage = "Please enter publish year.")]

        public Nullable<int> Copyright { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Date")]
        [Required(ErrorMessage = "Please select date")]
        public string DateAdded { get; set; }
        [DisplayName("Status")]
        [Required(ErrorMessage = "Please Select status.")]
        public string Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
